image: gitpod/workspace-full

tasks:
  - init: npm ci && npm run build && npm run test
    command: npm run dev

vscode:
  extensions:
    - svelte.svelte-vscode@104.0.0:bCbDpi01c0Qt+pqOeQV7Sw==
    - bierner.markdown-preview-github-styles@0.1.6:7Xkp16X2MuWg//+162XzKw==