name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node 🟢
        uses: actions/setup-node@v6
        with:
          node-version: 15

      - name: Install, build and test 🔧
        run: |
          npm install
          npm run build
          npm run test
          echo "google-site-verification: googleece5115d3add3491.html" > public/googleece5115d3add3491.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: public
